services:
  - type: web
    name: blogit-backend
    env: node
    buildCommand: npm run build:prod
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_URL
        sync: false
    healthCheckPath: /
    autoDeploy: true 